### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMaxScreenColumn' of undefined

### ISSUE THREAD

**Issue by skypuhui** [mark-hahn/markdown-scroll-sync#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v0.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getMaxScreenColumn' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1082

TypeError: Cannot read property 'getMaxScreenColumn' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1082:35)
  at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1036:20)
  at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1252:33)
  at /Users/benny/.atom/packages/markdown-scroll-sync/lib/main.coffee:51:25

```

### Commands

```
     -3:07.5 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:07.1 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  8x -3:03.4 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -2:40.9 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -2:16.7 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:59.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:57.4 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:52.8 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:49.7 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:41.4 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:47.4 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:43.9 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:41.9 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:41.2 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:32.3 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:30.2 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.6.2
Sublime-Style-Column-Selection, v1.2.3
atom-alignment, v0.11.0
atom-beautify, v0.21.4
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.1
autocomplete-snippets, v1.0.1
change-case, v0.5.1
color-picker, v1.4.4
emmet, v2.3.4
file-icons, v1.5.1
japanese-wrap, v0.2.4
markdown-scroll-sync, v0.1.1
minimap, v4.5.0
project-manager, v1.15.5
vim-mode, v0.36.0

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
Thanks very much for the report.  This is fixed in 0.1.2.

editor::bufferPositionForScreenPosition is throwing an exception I don't understand.  It is possible I'm sending in some bad params but I doubt it and it shouldn't throw no matter what.  I'm catching the exception now and writing debugging info to the console.log.  However, this patch in the code is harmless even if it never fully understood.

If you happen to see an error `markdown-scroll-sync: error in bufferPositionForScreenPosition` in the console I'd appreciate seeing the detailed output.  It may only happen when this package is combined with some other particular package.

**Comment by pascalpp** [comment]
FWIW I'm still seeing this error in 0.3.4.

![image](https://cloud.githubusercontent.com/assets/1355312/7780566/5f979312-00ae-11e5-9dd2-116273c15bfc.png)

![image](https://cloud.githubusercontent.com/assets/1355312/7780579/a796110c-00ae-11e5-9950-f8ff17b5f198.png)

Still learning my way around in Atom but this happens pretty regularly for me, so if you want more info on the issue I can get it for you.
